// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	CompanyID string
	ID        string
	TaskID    string
	Author    string
	Digest    string
	Bytes     int64
	State     string
	Verdict   string
	Verifier  pgtype.Text
	Contract  string
}

type ArtifactStaging struct {
	CompanyID string
	ID        string
	TaskID    string
	Digest    string
}

type Company struct {
	ID         string
	CompanySeq int64
}

type Employee struct {
	CompanyID string
	ID        string
	Epoch     int64
}

type Event struct {
	CompanyID  string
	CompanySeq int64
	Kind       string
	Payload    []byte
	Observed   bool
}

type Message struct {
	CompanyID  string
	ID         string
	MissionID  string
	TaskID     string
	Sender     string
	Recipient  string
	Kind       string
	Body       string
	EvidenceID pgtype.Text
}

type Mission struct {
	CompanyID    string
	ID           string
	State        string
	ActivationID pgtype.Text
	Contract     string
}

type Obligation struct {
	CompanyID  string
	ID         string
	TaskID     string
	Owner      string
	State      string
	EvidenceID pgtype.Text
}

type Receipt struct {
	CompanyID   string
	Actor       string
	Key         string
	Fingerprint string
	Result      []byte
}

type RuntimeControl struct {
	Singleton   bool
	Incarnation string
}

type Task struct {
	CompanyID  string
	ID         string
	MissionID  string
	Owner      string
	Kind       string
	State      string
	Generation int64
	Plan       []byte
}

type WorkerCheck struct {
	CompanyID string
	ID        string
	SessionID string
	Digest    string
	Phase     string
	Passed    bool
	Report    []byte
}

type WorkerCheckpoint struct {
	CompanyID string
	ID        string
	SessionID string
	Digest    string
	Data      []byte
}

type WorkerObservation struct {
	CompanyID string
	ID        string
	SessionID string
	Reason    string
	Data      []byte
}

type WorkerSession struct {
	CompanyID        string
	ID               string
	EmployeeID       string
	TaskID           string
	Generation       int64
	Epoch            int64
	Incarnation      string
	Profile          string
	State            string
	CapabilityDigest pgtype.Text
	ProcessPid       pgtype.Int8
	StopReceipt      pgtype.Text
}

type WorkerWorkspace struct {
	CompanyID string
	TaskID    string
	Digest    string
	Revision  int64
}
