// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
)

const listArtifacts = `-- name: ListArtifacts :many
SELECT a.id,a.digest,a.state,a.verdict FROM artifacts a JOIN tasks t
ON t.company_id=a.company_id AND t.id=a.task_id
WHERE a.company_id=$1 AND t.mission_id=$2 ORDER BY a.id
`

type ListArtifactsParams struct {
	CompanyID string
	MissionID string
}

type ListArtifactsRow struct {
	ID      string
	Digest  string
	State   string
	Verdict string
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts, arg.CompanyID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsRow{}
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Digest,
			&i.State,
			&i.Verdict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id FROM employees WHERE company_id=$1 ORDER BY id
`

func (q *Queries) ListEmployees(ctx context.Context, companyID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id FROM messages WHERE company_id=$1 AND mission_id=$2 ORDER BY id
`

type ListMessagesParams struct {
	CompanyID string
	MissionID string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.CompanyID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObligations = `-- name: ListObligations :many
SELECT o.id,o.state FROM obligations o JOIN tasks t
ON t.company_id=o.company_id AND t.id=o.task_id
WHERE o.company_id=$1 AND t.mission_id=$2 ORDER BY o.id
`

type ListObligationsParams struct {
	CompanyID string
	MissionID string
}

type ListObligationsRow struct {
	ID    string
	State string
}

func (q *Queries) ListObligations(ctx context.Context, arg ListObligationsParams) ([]ListObligationsRow, error) {
	rows, err := q.db.Query(ctx, listObligations, arg.CompanyID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObligationsRow{}
	for rows.Next() {
		var i ListObligationsRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, mission_id, owner, kind, state, generation FROM tasks
WHERE company_id=$1 AND mission_id=$2 ORDER BY id
`

type ListTasksParams struct {
	CompanyID string
	MissionID string
}

type ListTasksRow struct {
	ID         string
	MissionID  string
	Owner      string
	Kind       string
	State      string
	Generation int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.CompanyID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.Owner,
			&i.Kind,
			&i.State,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCompany = `-- name: LockCompany :one
SELECT id FROM companies WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCompany(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockCompany, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
