param([string]$OutputDirectory = "evidence/development/r0.3a-t8")
$ErrorActionPreference = "Stop"
$utf8 = [Text.UTF8Encoding]::new($false)
$sha = [Security.Cryptography.SHA256]::Create()
function Hash-Text([string]$Text){if($null -eq $Text){return $null};([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($Text))).Replace('-','')).ToLowerInvariant()}
function File-Manifest([string]$Path,[string]$Class){if(!(Test-Path -LiteralPath $Path)){return [pscustomobject]@{present=$false;class=$Class;path_category='not_found';sha256=$null;bytes=$null}};$f=Get-Item -LiteralPath $Path;[pscustomobject]@{present=$true;class=$Class;path_category=if($Path -match '\.runtime|/home/codex'){'ephemeral_runtime'}else{'user_profile_or_install'};sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLower();bytes=$f.Length}}
function Env-Manifest([string[]]$Names){$out=@();foreach($n in $Names){$v=[Environment]::GetEnvironmentVariable($n);$cat='absent';if($v){if($n -match 'PROXY'){$cat=if($v -match '127\.0\.0\.1|localhost'){'localhost_proxy'}else{'non_local_proxy'}}elseif($n -match 'BASE|ENDPOINT'){$cat='endpoint_override'}else{$cat='path_or_identity'}};$out += [pscustomobject]@{name=$n;present=[bool]$v;category=$cat;digest=if($v){Hash-Text $v}else{$null}}};$out}
function Config-Manifest([string]$Path,[string]$Class){$file=File-Manifest $Path $Class;if(!$file.present){return [pscustomobject]@{file=$file;keys=@();websocket='not_recorded';endpoint_override='not_recorded'}};$section='';$keys=@();$websocket=@();$endpoint=@();foreach($line in Get-Content -LiteralPath $Path){$trim=$line.Trim();if($trim -match '^\[(.+)\]$'){$section=$Matches[1];continue};if($trim -match '^([A-Za-z0-9_.-]+)\s*=\s*(.+)$'){$key=$Matches[1];$value=$Matches[2].Trim();$full=if($section){"$section.$key"}else{$key};$category=if($value -match '^(true|false)$'){"boolean:$value"}elseif($value -match '^".*"$'){'string'}else{'other'};$semantic=$null;if($full -in @('model','model_reasoning_effort','sandbox_mode') -or $full -match 'websocket'){$semantic=$value.Trim('"')};$keys += [pscustomobject]@{name=$full;category=$category;semantic=$semantic;digest=Hash-Text $value};if($full -match 'websocket'){$websocket += [pscustomobject]@{name=$full;category=$category;semantic=$semantic}};if($full -match 'model_providers\..*\.base_url|(^|\.)(OPENAI_BASE_URL|OPENAI_API_BASE|CODEX_BASE_URL)$'){$endpoint += [pscustomobject]@{name=$full;present=$true;digest=Hash-Text $value}}}};[pscustomobject]@{file=$file;keys=$keys;websocket=$websocket;endpoint_override=$endpoint}}
function Process-Manifest(){try{$all=Get-CimInstance Win32_Process;$selected=@($all|Where-Object{$_.Name -match '^(codex|codex-code-mode-host|ChatGPT).*'});$out=@();foreach($p in $selected){$parent=$all|Where-Object ProcessId -eq $p.ParentProcessId|Select-Object -First 1;$cmd=[string]$p.CommandLine;$out += [pscustomobject]@{name=$p.Name;pid=$p.ProcessId;parent_name=if($parent){$parent.Name}else{'not_recorded'};executable_category=if($p.ExecutablePath -match 'WindowsApps'){'desktop_app'}elseif($p.ExecutablePath -match 'OpenAI\\Codex\\bin'){'codex_install'}else{'other'};executable_path_digest=Hash-Text ([string]$p.ExecutablePath);command_line_digest=Hash-Text $cmd;flags=[pscustomobject]@{app_server=($cmd -match 'app-server');stdio=($cmd -match '--stdio');resume=($cmd -match 'resume');sandbox=($cmd -match 'sandbox')}}};return $out}catch{return @()}}
function Windows-Proxy-Manifest(){$raw=(& netsh winhttp show proxy|Out-String);$reg=Get-ItemProperty -LiteralPath 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -ErrorAction SilentlyContinue;$category=if($null -ne $reg -and [bool]$reg.ProxyEnable){'configured'}elseif($raw -match 'Direct access'){'direct'}else{'unknown'};[pscustomobject]@{winhttp_category=$category;winhttp_digest=Hash-Text $raw;user_proxy_enabled=if($null -ne $reg){[bool]$reg.ProxyEnable}else{$null};user_proxy_present=if($null -ne $reg){[bool]$reg.ProxyServer}else{$false};user_proxy_digest=if($null -ne $reg -and $reg.ProxyServer){Hash-Text ([string]$reg.ProxyServer)}else{$null};auto_config_present=if($null -ne $reg){[bool]$reg.AutoConfigURL}else{$false};auto_config_digest=if($null -ne $reg -and $reg.AutoConfigURL){Hash-Text ([string]$reg.AutoConfigURL)}else{$null}}}
$root=(Get-Location).Path
$aExe=(Get-Command codex.exe -ErrorAction Stop).Path
$aHome=Join-Path $env:USERPROFILE '.codex'
$aConfig=Join-Path $aHome 'config.toml';$aAuth=Join-Path $aHome 'auth.json';$aHost=Join-Path (Split-Path $aExe) 'codex-code-mode-host.exe'
$bExe=Join-Path $root '.tools/codex-linux/package/vendor/x86_64-unknown-linux-musl/bin/codex';$bHost=Join-Path (Split-Path $bExe) 'codex-code-mode-host';$bConfig=Join-Path $root '.runtime/linux/r03a-t6/canary/home/config.toml'
$t6=Get-Content -Raw (Join-Path $root 'evidence/development/r0.3a-t6/luna-1/readiness-manifest.json')|ConvertFrom-Json
$ready=$t6.readiness
$a=[pscustomobject]@{name='A_working_codex_desktop_cli';executable=File-Manifest $aExe 'windows_codex_executable';version=((& $aExe --version)|Out-String).Trim();code_mode_host=File-Manifest $aHost 'windows_code_mode_host';runtime='windows_x64_desktop';cwd=$root;home=[pscustomobject]@{HOME='absent_env_default_windows_profile';CODEX_HOME='absent_env_default_user_dot_codex'};config=Config-Manifest $aConfig 'user_codex_config';auth=File-Manifest $aAuth 'user_auth_file_opaque_fingerprint';env=Env-Manifest @('HTTP_PROXY','HTTPS_PROXY','ALL_PROXY','NO_PROXY','POLIS_NATIVE_PROXY','OPENAI_BASE_URL','OPENAI_API_BASE');processes=Process-Manifest;transport=[pscustomobject]@{websocket='config_or_default';http_sse='cannot_determine_without_live_run';system_proxy=Windows-Proxy-Manifest;native_proxy='absent_in_observed_shell'};callback_ipc='current process observed but endpoint not recorded'}
$bEnv=@([pscustomobject]@{name='HOME';present=$true;category='fixed_/home/codex';digest=Hash-Text '/home/codex'},[pscustomobject]@{name='CODEX_HOME';present=$true;category='fixed_/home/codex';digest=Hash-Text '/home/codex'},[pscustomobject]@{name='HTTP_PROXY';present=$true;category='localhost_proxy';digest=$ready.proxy_config_digest},[pscustomobject]@{name='HTTPS_PROXY';present=$true;category='localhost_proxy';digest=$ready.proxy_config_digest},[pscustomobject]@{name='ALL_PROXY';present=$false;category='absent';digest=$null},[pscustomobject]@{name='NO_PROXY';present=$false;category='absent';digest=$null},[pscustomobject]@{name='POLIS_NATIVE_PROXY';present=$false;category='controller_only_not_child_name';digest=$ready.proxy_config_digest},[pscustomobject]@{name='OPENAI_BASE_URL';present=$false;category='absent';digest=$null})
$b=[pscustomobject]@{name='B_polis_t6_app_server';executable=File-Manifest $bExe 'linux_pinned_codex_executable';version=$ready.native_version;code_mode_host=File-Manifest $bHost 'linux_code_mode_host';runtime='wsl_linux_amd64_bwrap';cwd='/work';home=[pscustomobject]@{HOME='explicit_/home/codex';CODEX_HOME='explicit_/home/codex'};config=Config-Manifest $bConfig 'generated_native_config';auth=File-Manifest $aAuth 'same_host_auth_file_ro_bound_to_/home/codex/auth.json';env=$bEnv;processes='historical_process_tree_not_recorded';launch_flags=@('bwrap','--unshare-all','--share-net','--die-with-parent','--new-session','--clearenv','--setenv HOME','--setenv CODEX_HOME','--setenv HTTP_PROXY','--setenv HTTPS_PROXY','/codex app-server --stdio');transport=[pscustomobject]@{websocket='explicit_disabled';http_sse='response_stream_used_exact_fallback_not_recorded';system_proxy='not_inherited_due_clearenv';native_proxy='localhost_HTTP_PROXY_and_HTTPS_PROXY'};callback_ipc='code_mode_host_present_zero_tools_callback_not_applicable'}
$c=[pscustomobject]@{name='C_bare_app_server_no_turn_preflight';executable=$b.executable;version=$b.version;code_mode_host=$b.code_mode_host;runtime=$b.runtime;cwd='/work';home=$b.home;config=$b.config;auth=$b.auth;env=$b.env;launch_flags=$b.launch_flags;transport=$b.transport;callback_ipc='app_server_initialized_thread_started_no_turn';evidence='evidence/development/r0.3a-real/luna-1/preflight-native/protocol.jsonl'}
$aModel=($a.config.keys|Where-Object name -eq 'model'|Select-Object -First 1).semantic;$aEffort=($a.config.keys|Where-Object name -eq 'model_reasoning_effort'|Select-Object -First 1).semantic;$aAppServer=@($a.processes|Where-Object{$_.name -eq 'codex.exe' -and $_.flags.app_server});$aStdio=@($aAppServer|Where-Object{$_.flags.stdio}).Count -gt 0
$matrix=@(
 [pscustomobject]@{field='executable_path_and_binary';classification='confirmed_different';A=$a.executable.sha256;B=$b.executable.sha256;C=$c.executable.sha256},
 [pscustomobject]@{field='codex_version';classification=if($a.version -eq $b.version){'confirmed_same'}else{'confirmed_different'};A=$a.version;B=$b.version;C=$c.version},
 [pscustomobject]@{field='runtime_profile';classification='confirmed_different';A=$a.runtime;B=$b.runtime;C=$c.runtime},
 [pscustomobject]@{field='cwd';classification='confirmed_different';A=$a.cwd;B=$b.cwd;C=$c.cwd},
 [pscustomobject]@{field='HOME_CODEX_HOME';classification='confirmed_different';A='env_absent_default_user_profile';B='explicit_/home/codex';C='explicit_/home/codex'},
 [pscustomobject]@{field='config_path_and_digest';classification=if(!$b.config.file.present){'not_recorded/cannot_compare_actual_B_file'}elseif($a.config.file.sha256 -eq $b.config.file.sha256){'confirmed_same'}else{'confirmed_different'};A=$a.config.file.sha256;B=$b.config.file.sha256;C=$c.config.file.sha256},
 [pscustomobject]@{field='auth_source_file_fingerprint';classification=if($a.auth.sha256 -eq $b.auth.sha256){'confirmed_same'}else{'confirmed_different'};A=$a.auth.sha256;B=$b.auth.sha256;C=$c.auth.sha256},
 [pscustomobject]@{field='HTTP_HTTPS_PROXY_env';classification='confirmed_different';A='absent_in_observed_shell';B='localhost_proxy_injected';C='localhost_proxy_injected'},
 [pscustomobject]@{field='POLIS_NATIVE_PROXY_env';classification='confirmed_different';A='absent';B='controller_source_then_HTTP(S)_PROXY_child';C='same_as_B'},
 [pscustomobject]@{field='websocket_config';classification='confirmed_different_configuration';A='config_or_default';B='explicit_disabled';C='explicit_disabled'},
 [pscustomobject]@{field='model_effort_defaults';classification=if($aModel -eq 'gpt-5.6-luna' -and $aEffort -eq 'medium'){'confirmed_same'}else{'confirmed_different'};A=("model={0},effort={1}" -f $aModel,$aEffort);B='model=gpt-5.6-luna,effort=medium';C='model=gpt-5.6-luna,effort=thread-registration-only'},
 [pscustomobject]@{field='app_server_stdio';classification=if($aStdio){'confirmed_same'}else{'confirmed_different'};A=if($aStdio){'app-server --stdio observed'}else{'app-server observed without --stdio'};B='app-server --stdio';C='app-server --stdio'},
 [pscustomobject]@{field='HTTP_SSE_fallback_runtime';classification='not_recorded/cannot_determine_without_live_run';A=$a.transport.http_sse;B=$b.transport.http_sse;C='no_turn'},
 [pscustomobject]@{field='OpenAI_Codex_endpoint_override';classification=if(@($a.config.endpoint_override).Count -eq 0){'confirmed_same_at_manifest_absent'}else{'confirmed_different'};A=if(@($a.config.endpoint_override).Count -eq 0){'absent'}else{'present_digest_only'};B='absent';C='absent'},
 [pscustomobject]@{field='process_ancestry';classification='not_recorded/cannot_compare_historical_B';A='captured_current_non_sensitive';B='historical_not_recorded';C='historical_not_recorded'},
 [pscustomobject]@{field='callback_local_IPC';classification='not_recorded/cannot_compare';A=$a.callback_ipc;B=$b.callback_ipc;C=$c.callback_ipc}
)
$output=[pscustomobject]@{generated_at=(Get-Date).ToUniversalTime().ToString('o');safety='no provider call; no secret values recorded';A=$a;B=$b;C=$c;matrix=$matrix;first_confirmed_divergence='process envelope: Windows installed codex.exe/default user home versus pinned Linux codex under WSL+bwrap with generated home/config';first_transport_relevant_divergence='A observed proxy environment absent; B/C inject localhost HTTP_PROXY and HTTPS_PROXY from POLIS_NATIVE_PROXY'}
New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null
$output|ConvertTo-Json -Depth 100|Set-Content -LiteralPath (Join-Path $OutputDirectory 'execution-diff.json') -Encoding UTF8
$md=@('# R0.3A-T8 working Codex vs Polis native execution differential','',('First confirmed divergence: '+$output.first_confirmed_divergence),('',('First transport-relevant divergence: '+$output.first_transport_relevant_divergence)),'','## Matrix')
foreach($m in $matrix){$md += ('- '+$m.field+': `'+$m.classification+'`; A='+$m.A+'; B='+$m.B+'; C='+$m.C+'.')}
$md|Set-Content -LiteralPath (Join-Path $OutputDirectory 'execution-diff.md') -Encoding UTF8
Write-Output "wrote $OutputDirectory"
